# -*- coding: utf-8 -*-
"""Ürün verisi — her alan {tr, en} çiftidir. Site bu dosyadan üretilir."""

CATEGORIES = {
    "kuruyemis": {"tr": "Kuruyemiş", "en": "Nuts"},
    "cekirdek":  {"tr": "Çekirdek & Leblebi", "en": "Seeds & Roasted Chickpeas"},
    "kurumeyve": {"tr": "Kuru Meyve", "en": "Dried Fruits"},
}

# Ortak ambalaj seçenekleri
PACKAGING = {
    "tr": ["10 kg vakumlu karton koli", "12,5 / 25 kg karton koli (PE iç torbalı)",
           "25 / 50 kg PP veya jüt çuval", "Perakende: 100 g – 1 kg doypack / kavanoz (private label)"],
    "en": ["10 kg vacuum-packed carton", "12.5 / 25 kg carton with PE liner",
           "25 / 50 kg PP or jute bag", "Retail: 100 g – 1 kg doypack / jar (private label)"],
}

PRODUCTS = [
  {
    "slug": "ceviz", "slug_en": "walnuts", "cat": "kuruyemis", "img": "ceviz", "gallery": 3, "featured": True,
    "name": {"tr": "Ceviz", "en": "Walnuts"},
    "latin": "Juglans regia",
    "tagline": {"tr": "Açık renkli, dolgun iç; kabuklu ve iç ceviz seçenekleri",
                "en": "Light-coloured, full kernels — in-shell and shelled"},
    "intro": {
      "tr": "Ceviz, yüksek Omega-3 (ALA) içeriği ve karakteristik aromasıyla hem doğrudan tüketimde hem de pastacılık ve gıda sanayiinde en çok talep gören kuruyemişlerden biridir. Asya Çerez olarak iç rengi, doluluk oranı ve nem değeri kontrol edilmiş partileri; kabuklu ve iç ceviz olarak toptan ve ihracata uygun ambalajlarla sunuyoruz.",
      "en": "Rich in plant-based Omega-3 (ALA) and prized for its distinctive flavour, the walnut is one of the most sought-after nuts for direct consumption, bakery and food manufacturing. Asya Çerez supplies lots checked for kernel colour, fill ratio and moisture — both in-shell and shelled — in wholesale and export-ready packaging."},
    "details": {
      "tr": ["Kabuklu cevizde Chandler, Howard ve yerli seçme çeşitler; kabuk bütünlüğü ve kolay kırılabilirlik esas alınır.",
             "İç cevizde renk sınıflaması USDA skalasına göre yapılır: Extra Light, Light, Light Amber.",
             "Kelebek (yarım), çeyrek ve parça iç formlarında pastacılık ve sanayi için uygun seçenekler sunulur.",
             "Her parti için nem, yabancı madde ve duyusal analiz yapılır; talep halinde akredite laboratuvar raporu sağlanır."],
      "en": ["In-shell: Chandler, Howard and selected domestic varieties — graded for shell integrity and easy cracking.",
             "Kernels graded on the USDA colour chart: Extra Light, Light, Light Amber.",
             "Halves, quarters and pieces available for bakery and industrial use.",
             "Each lot is checked for moisture, foreign matter and sensory quality; accredited lab reports on request."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Ege, İç Anadolu), ABD (Kaliforniya), Şili, Özbekistan", "en": "Türkiye (Aegean, Central Anatolia), USA (California), Chile, Uzbekistan"},
      "forms":   {"tr": "Kabuklu, iç kelebek, iç çeyrek, iç parça", "en": "In-shell, halves, quarters, pieces"},
      "grades":  {"tr": "Kabuklu: 28-30 / 30-32 / 32-34 / 34+ mm · İç: Extra Light Halves, Light Halves, Light Quarters, Light Amber Pieces", "en": "In-shell: 28-30 / 30-32 / 32-34 / 34+ mm · Kernels: Extra Light Halves, Light Halves, Light Quarters, Light Amber Pieces"},
      "moisture":{"tr": "≤ %8", "en": "≤ 8%"},
      "shelf":   {"tr": "Uygun koşullarda 12 ay", "en": "12 months under proper storage"},
      "hs":      "0802.31 (kabuklu / in-shell) · 0802.32 (iç / shelled)",
    },
    "nutrition": [654, 15.2, 65.2, 13.7, 6.7],
  },
  {
    "slug": "badem", "slug_en": "almonds", "cat": "kuruyemis", "img": "badem", "gallery": 3, "featured": True,
    "name": {"tr": "Badem", "en": "Almonds"},
    "latin": "Prunus dulcis",
    "tagline": {"tr": "Çiğ, kavrulmuş, beyazlatılmış ve işlenmiş formlarda", "en": "Natural, roasted, blanched and processed forms"},
    "intro": {
      "tr": "Protein, lif ve E vitamini açısından zengin badem; çerezlikten çikolata ve unlu mamul sanayiine kadar çok geniş bir kullanım alanına sahiptir. Kaliforniya, İspanya ve Türkiye menşeli bademleri adet/ons kalibrasyonuyla, standart ve özel işlenmiş formlarda tedarik ediyoruz.",
      "en": "High in protein, fibre and vitamin E, almonds serve everything from snacking to chocolate and bakery production. We supply Californian, Spanish and Turkish almonds, graded by count per ounce, in standard and custom-processed forms."},
    "details": {
      "tr": ["Nonpareil, Carmel, Independence ve Akdeniz tipi (Datça, Ferragnès) çeşitler.",
             "Çiğ (natürel), kavrulmuş, tuzlu, beyazlatılmış (blanched), dilimlenmiş, file, çubuk ve badem unu seçenekleri.",
             "Kalibre adet/ons olarak belirlenir; ürün kullanım amacına göre en uygun boy önerilir.",
             "Aflatoksin ve pestisit değerleri AB ve alıcı ülke mevzuatına uygun partilerden seçilir."],
      "en": ["Nonpareil, Carmel, Independence and Mediterranean types (Datça, Ferragnès).",
             "Natural, roasted, salted, blanched, sliced, slivered, diced and almond flour.",
             "Sized by count per ounce — we recommend the best fit for your application.",
             "Lots selected to meet EU and destination-country limits for aflatoxin and pesticide residues."]},
    "specs": {
      "origin":  {"tr": "ABD (Kaliforniya), İspanya, Türkiye, Avustralya", "en": "USA (California), Spain, Türkiye, Australia"},
      "forms":   {"tr": "Kabuklu, iç natürel, kavrulmuş, beyazlatılmış, dilimlenmiş, un", "en": "In-shell, natural kernels, roasted, blanched, sliced, flour"},
      "grades":  {"tr": "18/20 · 20/22 · 23/25 · 25/27 · 27/30 adet/ons", "en": "18/20 · 20/22 · 23/25 · 25/27 · 27/30 count per ounce"},
      "moisture":{"tr": "≤ %6", "en": "≤ 6%"},
      "shelf":   {"tr": "Uygun koşullarda 18 ay", "en": "18 months under proper storage"},
      "hs":      "0802.11 (kabuklu / in-shell) · 0802.12 (iç / shelled)",
    },
    "nutrition": [579, 21.2, 49.9, 21.6, 12.5],
  },
  {
    "slug": "findik", "slug_en": "hazelnuts", "cat": "kuruyemis", "img": "findik", "gallery": 2, "featured": True,
    "name": {"tr": "Fındık", "en": "Hazelnuts"},
    "latin": "Corylus avellana",
    "tagline": {"tr": "Karadeniz'in dünyaca ünlü fındığı — Giresun Tombul & Levant", "en": "World-famous Black Sea hazelnuts — Giresun Tombul & Levant"},
    "intro": {
      "tr": "Türkiye, dünya fındık üretiminin yaklaşık üçte ikisini karşılayan lider ülkedir. Karadeniz'in iklimiyle olgunlaşan fındık; yoğun aroması, yüksek yağ ve protein değeriyle çikolata, pralin ve şekerleme sanayiinin vazgeçilmezidir. Kabuklu fındıktan fındık ezmesine kadar tüm formlarda, kalibre ve kaliteye göre ayrılmış partiler sunuyoruz.",
      "en": "Türkiye grows roughly two-thirds of the world's hazelnuts. Ripened in the Black Sea climate, Turkish hazelnuts are valued for intense aroma and high oil and protein content — essential to the chocolate, praline and confectionery industries. We supply every form, from in-shell to paste, in lots sorted by size and quality."},
    "details": {
      "tr": ["Giresun Kalite (Tombul) ve Levant Kalite (Ordu, Samsun, Trabzon, Düzce) seçenekleri.",
             "Natürel iç, kavrulmuş (derisi soyulmuş), pirinç (kıyılmış), dilimlenmiş, fındık unu ve fındık ezmesi.",
             "Kalibre elekten geçirme ile milimetre bazında ayrılır; sağlam, çürüksüz ve böcek hasarsız iç oranı raporlanır.",
             "Kavurma derecesi ve renk, alıcının üretim hattına göre ayarlanabilir."],
      "en": ["Giresun Quality (Tombul) and Levant Quality (Ordu, Samsun, Trabzon, Düzce).",
             "Natural kernels, roasted & blanched, diced, sliced, hazelnut flour and paste.",
             "Screened to the millimetre; sound-kernel ratio (no rot, no insect damage) reported per lot.",
             "Roast level and colour can be tuned to your production line."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Giresun, Ordu, Samsun, Trabzon, Düzce)", "en": "Türkiye (Giresun, Ordu, Samsun, Trabzon, Düzce)"},
      "forms":   {"tr": "Kabuklu, natürel iç, kavrulmuş, pirinç, dilim, un, ezme", "en": "In-shell, natural kernels, roasted, diced, sliced, flour, paste"},
      "grades":  {"tr": "9-11 · 11-13 · 13-15 mm ve karışık kalibre", "en": "9-11 · 11-13 · 13-15 mm and mixed sizes"},
      "moisture":{"tr": "≤ %6", "en": "≤ 6%"},
      "shelf":   {"tr": "Natürel: 12 ay · Kavrulmuş: 9 ay", "en": "Natural: 12 months · Roasted: 9 months"},
      "hs":      "0802.21 (kabuklu / in-shell) · 0802.22 (iç / shelled)",
    },
    "nutrition": [628, 15.0, 60.8, 16.7, 9.7],
  },
  {
    "slug": "antep-fistigi", "slug_en": "pistachios", "cat": "kuruyemis", "img": "antep-fistigi", "gallery": 4, "featured": True,
    "name": {"tr": "Antep Fıstığı", "en": "Pistachios"},
    "latin": "Pistacia vera",
    "tagline": {"tr": "Gaziantep ve Siirt fıstığı; kavrulmuş, çiğ ve yeşil iç", "en": "Antep & Siirt pistachios — roasted, raw and green kernels"},
    "intro": {
      "tr": "Güneydoğu Anadolu'nun güneşiyle olgunlaşan Antep fıstığı, yoğun aroması ve canlı yeşil rengiyle dünya mutfağının en değerli kuruyemişlerindendir. Kavrulmuş tuzlu kabuklu fıstıktan baklava ve dondurma sanayiine yönelik boz (yeşil) iç fıstığa kadar geniş bir ürün yelpazesi sunuyoruz.",
      "en": "Ripened under the South-Eastern Anatolian sun, pistachios are among the most valued nuts in world cuisine for their rich flavour and vivid green colour. Our range spans roasted & salted in-shell pistachios to the early-harvest green kernels used in baklava and gelato."},
    "details": {
      "tr": ["Gaziantep (Antep) fıstığı: küçük taneli, yoğun aromalı; Siirt fıstığı: iri, dolgun taneli.",
             "Boz iç (erken hasat yeşil iç): baklava, lokum, dondurma ve pastacılık için yoğun yeşil renk.",
             "Kavrulmuş tuzlu, kavrulmuş tuzsuz, limonlu ve çiğ kabuklu seçenekler.",
             "Açık ağız oranı, iç rengi ve kalibre her parti için kontrol edilir."],
      "en": ["Antep pistachio: small, intensely aromatic; Siirt pistachio: large, plump kernels.",
             "Green kernels (early harvest): deep green colour for baklava, Turkish delight, gelato and pastry.",
             "Roasted salted, roasted unsalted, lemon-flavoured and raw in-shell options.",
             "Split ratio, kernel colour and size checked for every lot."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Gaziantep, Şanlıurfa, Siirt), İran, ABD", "en": "Türkiye (Gaziantep, Şanlıurfa, Siirt), Iran, USA"},
      "forms":   {"tr": "Kabuklu çiğ / kavrulmuş, boz (yeşil) iç, iç fıstık, pirinç", "en": "In-shell raw / roasted, green kernels, kernels, diced"},
      "grades":  {"tr": "Kabuklu: 18/20 · 20/22 · 22/24 · 26/28 adet/ons", "en": "In-shell: 18/20 · 20/22 · 22/24 · 26/28 count per ounce"},
      "moisture":{"tr": "≤ %6", "en": "≤ 6%"},
      "shelf":   {"tr": "Uygun koşullarda 12 ay", "en": "12 months under proper storage"},
      "hs":      "0802.51 (kabuklu / in-shell) · 0802.52 (iç / shelled)",
    },
    "nutrition": [562, 20.2, 45.3, 27.2, 10.6],
  },
  {
    "slug": "kaju", "slug_en": "cashews", "cat": "kuruyemis", "img": "kaju", "gallery": 3, "featured": True,
    "name": {"tr": "Kaju", "en": "Cashews"},
    "latin": "Anacardium occidentale",
    "tagline": {"tr": "W180'den W450'ye tam kalibre yelpazesi", "en": "Full grade range from W180 to W450"},
    "intro": {
      "tr": "Yumuşak dokusu ve hafif tatlı lezzetiyle kaju, çerez karışımlarından vegan gıda üretimine kadar hızla büyüyen bir talebe sahiptir. Vietnam, Hindistan ve Batı Afrika menşeli kajuları uluslararası AFI kalite standartlarına göre sınıflandırılmış olarak tedarik ediyoruz.",
      "en": "With its creamy texture and mildly sweet taste, cashew demand keeps growing — from snack mixes to plant-based foods. We source Vietnamese, Indian and West African cashews graded to international AFI standards."},
    "details": {
      "tr": ["Bütün beyaz iç: W180 (en iri), W210, W240, W320, W450.",
             "Kırık formlar: Splits (S), Butts (B), Large White Pieces (LWP) — sanayi için ekonomik çözümler.",
             "Çiğ, kavrulmuş, tuzlu ve aromalı kavrulmuş seçenekler.",
             "Vakumlu / azot dolumlu teneke ve karton ambalajla tazelik korunur."],
      "en": ["Whole white kernels: W180 (largest), W210, W240, W320, W450.",
             "Broken grades: Splits (S), Butts (B), Large White Pieces (LWP) — cost-effective for industry.",
             "Raw, roasted, salted and flavoured roasted options.",
             "Vacuum / nitrogen-flushed tins and cartons keep kernels fresh."]},
    "specs": {
      "origin":  {"tr": "Vietnam, Hindistan, Fildişi Sahili, Tanzanya", "en": "Vietnam, India, Côte d'Ivoire, Tanzania"},
      "forms":   {"tr": "Bütün iç, yarım, kırık; çiğ / kavrulmuş / tuzlu", "en": "Wholes, splits, pieces; raw / roasted / salted"},
      "grades":  {"tr": "W180 · W210 · W240 · W320 · W450 · S · B · LWP", "en": "W180 · W210 · W240 · W320 · W450 · S · B · LWP"},
      "moisture":{"tr": "≤ %5", "en": "≤ 5%"},
      "shelf":   {"tr": "Uygun koşullarda 12 ay", "en": "12 months under proper storage"},
      "hs":      "0801.32 (iç / shelled)",
    },
    "nutrition": [553, 18.2, 43.9, 30.2, 3.3],
  },
  {
    "slug": "yer-fistigi", "slug_en": "peanuts", "cat": "kuruyemis", "img": "yer-fistigi", "gallery": 3, "featured": False,
    "name": {"tr": "Yer Fıstığı", "en": "Peanuts"},
    "latin": "Arachis hypogaea",
    "tagline": {"tr": "Osmaniye yer fıstığı; kabuklu, iç, kavrulmuş", "en": "Osmaniye peanuts — in-shell, kernels, roasted"},
    "intro": {
      "tr": "Türkiye'de üretimin merkezi olan Osmaniye'nin yer fıstığı; iri tanesi, ince zarı ve belirgin aromasıyla öne çıkar. Çerezlik kabuklu fıstıktan fıstık ezmesi üretimine uygun ham içe kadar farklı formlarda, yerli ve ithal menşeli seçenekler sunuyoruz.",
      "en": "Osmaniye, the heart of Turkish peanut production, is known for large kernels, thin skins and a distinctive aroma. We offer domestic and imported peanuts in forms from in-shell snacking nuts to raw kernels for peanut butter."},
    "details": {
      "tr": ["Kabuklu kavrulmuş (tuzlu / tuzsuz), çiğ iç, beyazlatılmış (blanched) ve kavrulmuş iç.",
             "Runner, Virginia ve yerli NC-7 tipi çeşitler.",
             "Fıstık ezmesi ve şekerleme üretimine yönelik sanayi kalibreleri.",
             "Aflatoksin kontrolü her parti için zorunlu olarak yapılır."],
      "en": ["In-shell roasted (salted / unsalted), raw kernels, blanched and roasted kernels.",
             "Runner, Virginia and domestic NC-7 types.",
             "Industrial grades for peanut butter and confectionery.",
             "Aflatoxin testing mandatory for every lot."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Osmaniye, Adana), Arjantin, ABD", "en": "Türkiye (Osmaniye, Adana), Argentina, USA"},
      "forms":   {"tr": "Kabuklu, iç, beyazlatılmış, kavrulmuş, tuzlu", "en": "In-shell, kernels, blanched, roasted, salted"},
      "grades":  {"tr": "38/42 · 40/50 · 50/60 · 60/70 adet/ons", "en": "38/42 · 40/50 · 50/60 · 60/70 count per ounce"},
      "moisture":{"tr": "≤ %7", "en": "≤ 7%"},
      "shelf":   {"tr": "Uygun koşullarda 12 ay", "en": "12 months under proper storage"},
      "hs":      "1202.41 (kabuklu / in-shell) · 1202.42 (iç / shelled) · 2008.11 (kavrulmuş / roasted)",
    },
    "nutrition": [567, 25.8, 49.2, 16.1, 8.5],
  },
  {
    "slug": "karisik-kuruyemis", "slug_en": "mixed-nuts", "cat": "kuruyemis", "img": "karisik-kuruyemis", "gallery": 2, "featured": False,
    "name": {"tr": "Karışık Kuruyemiş", "en": "Mixed Nuts"},
    "latin": None,
    "tagline": {"tr": "Size özel oranlarla lüks ve ekonomik karışımlar", "en": "Premium and value blends mixed to your ratios"},
    "intro": {
      "tr": "Perakende rafları, oteller, havayolu ikramları ve hediye paketleri için; ceviz, badem, fındık, kaju, Antep fıstığı ve kuru meyvelerden oluşan karışımları istediğiniz oranda hazırlıyoruz. Kendi markanızla (private label) ambalajlama da mümkündür.",
      "en": "For retail shelves, hotels, airline catering and gift packs, we blend walnuts, almonds, hazelnuts, cashews, pistachios and dried fruits to the ratio you specify — with private-label packing available."},
    "details": {
      "tr": ["Lüks karışık: kaju, badem, fındık, Antep fıstığı ağırlıklı.",
             "Çiğ (raw) karışım, kavrulmuş tuzlu karışım ve kuru meyveli (trail mix) seçenekler.",
             "Oran, kalibre ve ambalaj tamamen alıcının şartnamesine göre belirlenir.",
             "Minimum sipariş miktarı karışım tipine göre birlikte planlanır."],
      "en": ["Deluxe mix: cashew, almond, hazelnut and pistachio led.",
             "Raw mix, roasted & salted mix and dried-fruit trail mix.",
             "Ratios, sizes and packaging set entirely by your specification.",
             "Minimum order quantity planned together depending on the blend."]},
    "specs": {
      "origin":  {"tr": "Bileşenlere göre çoklu menşe", "en": "Multi-origin depending on components"},
      "forms":   {"tr": "Çiğ, kavrulmuş, tuzlu, kuru meyveli", "en": "Raw, roasted, salted, with dried fruit"},
      "grades":  {"tr": "Alıcı şartnamesine göre", "en": "As per buyer specification"},
      "moisture":{"tr": "Bileşenlere göre", "en": "Depends on components"},
      "shelf":   {"tr": "6 – 12 ay", "en": "6 – 12 months"},
      "hs":      "2008.19 · 0813.50",
    },
    "nutrition": None,
  },
  {
    "slug": "ay-cekirdegi", "slug_en": "sunflower-seeds", "cat": "cekirdek", "img": "ay-cekirdegi", "gallery": 2, "featured": True,
    "name": {"tr": "Ay Çekirdeği", "en": "Sunflower Seeds"},
    "latin": "Helianthus annuus",
    "tagline": {"tr": "Çerezlik çizgili çekirdek ve iç ay çekirdeği", "en": "Striped confectionery seeds and hulled kernels"},
    "intro": {
      "tr": "Türkiye'nin en sevilen çerezi olan ay çekirdeğinde, kabuğu kolay açılan, iri ve dolgun çerezlik çeşitlere odaklanıyoruz. Kavrulmuş tuzlu, tuzsuz ve iç ay çekirdeğini hem perakende hem de sanayi (ekmek, müsli, bar) için tedarik ediyoruz.",
      "en": "Türkiye's favourite snack. We focus on large, plump confectionery varieties that crack easily, supplying roasted salted, unsalted and hulled kernels for both retail and industry (bread, muesli, bars)."},
    "details": {
      "tr": ["Siyah-beyaz çizgili çerezlik tipler (Trakya ve ithal çeşitler).",
             "Kalibre, 50 gramdaki tane sayısıyla belirlenir; iri taneler premium segmente yönlendirilir.",
             "Kavrulmuş tuzlu, az tuzlu, tuzsuz ve çiğ seçenekler.",
             "İç ay çekirdeği: fırıncılık ve müsli sanayii için Bakery grade."],
      "en": ["Black-and-white striped confectionery types (Thrace and imported varieties).",
             "Graded by seeds per 50 g; the largest sizes go to the premium segment.",
             "Roasted salted, lightly salted, unsalted and raw options.",
             "Hulled kernels: bakery grade for bread and muesli production."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Trakya), Ukrayna, Çin, Arjantin", "en": "Türkiye (Thrace), Ukraine, China, Argentina"},
      "forms":   {"tr": "Kabuklu çiğ / kavrulmuş, iç", "en": "In-shell raw / roasted, kernels"},
      "grades":  {"tr": "180-200 · 200-220 · 220-240 tane / 50 g", "en": "180-200 · 200-220 · 220-240 seeds / 50 g"},
      "moisture":{"tr": "≤ %7", "en": "≤ 7%"},
      "shelf":   {"tr": "Uygun koşullarda 12 ay", "en": "12 months under proper storage"},
      "hs":      "1206.00 · 2008.19 (kavrulmuş / roasted)",
    },
    "nutrition": [584, 20.8, 51.5, 20.0, 8.6],
  },
  {
    "slug": "kabak-cekirdegi", "slug_en": "pumpkin-seeds", "cat": "cekirdek", "img": "kabak-cekirdegi", "gallery": 1, "featured": False,
    "name": {"tr": "Kabak Çekirdeği", "en": "Pumpkin Seeds"},
    "latin": "Cucurbita pepo",
    "tagline": {"tr": "Nevşehir çerezlik beyaz çekirdek ve GWS yeşil iç", "en": "Nevşehir white snack seeds and GWS green kernels"},
    "intro": {
      "tr": "Kapadokya bölgesinin ünlü çerezlik beyaz kabak çekirdeği, iri ve beyaz kabuğu ile Türkiye pazarının en değerli çekirdeklerindendir. Buna ek olarak fırıncılık, salata ve sağlıklı atıştırmalık sektörüne yönelik kabuksuz (GWS) yeşil iç kabak çekirdeği sunuyoruz.",
      "en": "Cappadocia's famous white snack pumpkin seed, with its large, bright white shell, is among the most valued seeds in the Turkish market. We also supply shell-less (GWS) green pumpkin kernels for bakery, salads and healthy snacking."},
    "details": {
      "tr": ["Nevşehir / Kayseri çerezlik beyaz kabak çekirdeği — kavrulmuş tuzlu.",
             "GWS (Grown Without Shell) Shine Skin yeşil iç: AA ve A kalite.",
             "Magnezyum, çinko ve bitkisel protein açısından zengin.",
             "Kavurma ve tuzlama derecesi talebe göre ayarlanır."],
      "en": ["Nevşehir / Kayseri white snack pumpkin seeds — roasted & salted.",
             "GWS (Grown Without Shell) Shine Skin green kernels: AA and A grade.",
             "Rich in magnesium, zinc and plant protein.",
             "Roast and salt levels adjusted on request."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Nevşehir, Kayseri), Çin", "en": "Türkiye (Nevşehir, Kayseri), China"},
      "forms":   {"tr": "Kabuklu kavrulmuş, yeşil iç (çiğ / kavrulmuş)", "en": "In-shell roasted, green kernels (raw / roasted)"},
      "grades":  {"tr": "GWS AA · A · Bakery; kabuklu iri / orta", "en": "GWS AA · A · Bakery; in-shell large / medium"},
      "moisture":{"tr": "≤ %7", "en": "≤ 7%"},
      "shelf":   {"tr": "Uygun koşullarda 12 ay", "en": "12 months under proper storage"},
      "hs":      "1207.99 · 2008.19 (kavrulmuş / roasted)",
    },
    "nutrition": [559, 30.2, 49.1, 10.7, 6.0],
  },
  {
    "slug": "leblebi", "slug_en": "roasted-chickpeas", "cat": "cekirdek", "img": "leblebi", "gallery": 2, "featured": False,
    "name": {"tr": "Leblebi", "en": "Roasted Chickpeas (Leblebi)"},
    "latin": "Cicer arietinum",
    "tagline": {"tr": "Çorum'un geleneksel sarı ve beyaz leblebisi", "en": "Traditional yellow and white leblebi from Çorum"},
    "intro": {
      "tr": "Nohudun geleneksel yöntemlerle dinlendirilip birkaç aşamada kavrulmasıyla elde edilen leblebi, Anadolu'ya özgü bir lezzettir. Çorum'un ustalığıyla üretilen sarı, beyaz ve çifte kavrulmuş leblebiyi yüksek protein ve lif içeriğine sahip sağlıklı bir atıştırmalık olarak yurt içi ve yurt dışı pazarlara sunuyoruz.",
      "en": "Made by resting chickpeas and roasting them in several stages using traditional methods, leblebi is a uniquely Anatolian snack. We offer yellow, white and double-roasted leblebi made by Çorum's master roasters — a high-protein, high-fibre snack for domestic and international markets."},
    "details": {
      "tr": ["Sarı leblebi (kabuklu, çifte kavrulmuş), beyaz leblebi ve tuzlu / baharatlı çeşitler.",
             "Şekerli leblebi ve leblebi unu seçenekleri.",
             "Glütensiz, bitkisel protein ve lif kaynağı.",
             "Perakende ambalajda kendi markanızla (private label) üretim."],
      "en": ["Yellow leblebi (in-skin, double-roasted), white leblebi and salted / spiced varieties.",
             "Sugar-coated leblebi and leblebi flour.",
             "Gluten-free source of plant protein and fibre.",
             "Private-label production in retail packaging."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Çorum)", "en": "Türkiye (Çorum)"},
      "forms":   {"tr": "Sarı, beyaz, çifte kavrulmuş, tuzlu, şekerli, un", "en": "Yellow, white, double-roasted, salted, sugar-coated, flour"},
      "grades":  {"tr": "İri · orta · küçük", "en": "Large · medium · small"},
      "moisture":{"tr": "≤ %5", "en": "≤ 5%"},
      "shelf":   {"tr": "Uygun koşullarda 12 ay", "en": "12 months under proper storage"},
      "hs":      "2008.19",
    },
    "nutrition": [370, 21.0, 5.5, 58.0, 12.0],
  },
  {
    "slug": "kuru-kayisi", "slug_en": "dried-apricots", "cat": "kurumeyve", "img": "kuru-kayisi", "gallery": 1, "featured": True,
    "name": {"tr": "Kuru Kayısı", "en": "Dried Apricots"},
    "latin": "Prunus armeniaca",
    "tagline": {"tr": "Malatya kayısısı — kükürtlü ve gün kurusu", "en": "Malatya apricots — sulphured and sun-dried"},
    "intro": {
      "tr": "Türkiye, dünya kuru kayısı ticaretinin açık ara lideridir ve bu başarının merkezinde Malatya vardır. Güneşte doğal yollarla kurutulan kayısıları; parlak turuncu renkli kükürtlü ve katkısız, koyu renkli gün kurusu (natürel) olarak, kalibre ve renk sınıflandırmasıyla tedarik ediyoruz.",
      "en": "Türkiye leads world trade in dried apricots, with Malatya at its heart. We supply naturally sun-dried apricots — bright orange sulphured and additive-free dark sun-dried (natural) — graded by size and colour."},
    "details": {
      "tr": ["Kükürtlü (sarı) kuru kayısı: parlak renk, uzun raf ömrü.",
             "Gün kurusu (natürel / organik) kayısı: katkısız, doğal kahverengi.",
             "Bütün, çekirdeksiz (lokum tipi), küp doğranmış ve ezme formları.",
             "Kalibre kilogramdaki tane sayısına göre No.1 – No.8 olarak sınıflanır."],
      "en": ["Sulphured (orange) apricots: bright colour, long shelf life.",
             "Sun-dried (natural / organic): additive-free, naturally brown.",
             "Whole pitted, diced and paste forms.",
             "Graded No.1 – No.8 by pieces per kilogram."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Malatya, Elazığ)", "en": "Türkiye (Malatya, Elazığ)"},
      "forms":   {"tr": "Bütün çekirdeksiz, küp, ezme", "en": "Whole pitted, diced, paste"},
      "grades":  {"tr": "No.1 – No.8 (adet/kg)", "en": "No.1 – No.8 (pieces per kg)"},
      "moisture":{"tr": "%18 – 25", "en": "18 – 25%"},
      "shelf":   {"tr": "Uygun koşullarda 12 – 18 ay", "en": "12 – 18 months under proper storage"},
      "hs":      "0813.10",
    },
    "nutrition": [241, 3.4, 0.5, 62.6, 7.3],
  },
  {
    "slug": "kuru-incir", "slug_en": "dried-figs", "cat": "kurumeyve", "img": "kuru-incir", "gallery": 1, "featured": False,
    "name": {"tr": "Kuru İncir", "en": "Dried Figs"},
    "latin": "Ficus carica",
    "tagline": {"tr": "Aydın'ın Sarılop inciri; Lerida, Protoben, Garland", "en": "Aydın Sarılop figs — Lerida, Protoben, Garland"},
    "intro": {
      "tr": "Büyük Menderes havzasında yetişen Sarılop çeşidi Aydın inciri; ince kabuğu, bal gibi tatlı ve yumuşak dokusuyla dünyanın en kaliteli kuru inciri kabul edilir. Farklı pazarların beklentilerine göre şekillendirilmiş (Lerida, Protoben, Garland) ve natürel incirleri tedarik ediyoruz.",
      "en": "Grown in the Büyük Menderes basin, the Sarılop variety from Aydın — thin-skinned, honey-sweet and soft — is regarded as the finest dried fig in the world. We supply naturals and fig shapes tailored to each market (Lerida, Protoben, Garland)."},
    "details": {
      "tr": ["Lerida (yuvarlak, bastırılmış), Protoben (yassı), Garland (dizi) ve natürel formlar.",
             "Küp doğranmış incir ve incir ezmesi — unlu mamul ve bar sanayii için.",
             "Kalibre kilogramdaki adet sayısına göre belirlenir.",
             "Aflatoksin kontrolü UV lamba ile tek tek ayıklama sürecini içerir."],
      "en": ["Lerida (round, pressed), Protoben (flat), Garland (strung) and natural forms.",
             "Diced figs and fig paste for bakery and bar production.",
             "Graded by pieces per kilogram.",
             "Aflatoxin control includes piece-by-piece UV-lamp sorting."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Aydın, İzmir)", "en": "Türkiye (Aydın, İzmir)"},
      "forms":   {"tr": "Natürel, Lerida, Protoben, Garland, küp, ezme", "en": "Natural, Lerida, Protoben, Garland, diced, paste"},
      "grades":  {"tr": "Jumbo · No.1 – No.7 (adet/kg)", "en": "Jumbo · No.1 – No.7 (pieces per kg)"},
      "moisture":{"tr": "≤ %24", "en": "≤ 24%"},
      "shelf":   {"tr": "Uygun koşullarda 12 ay", "en": "12 months under proper storage"},
      "hs":      "0804.20",
    },
    "nutrition": [249, 3.3, 0.9, 63.9, 9.8],
  },
  {
    "slug": "kuru-uzum", "slug_en": "raisins", "cat": "kurumeyve", "img": "kuru-uzum", "gallery": 1, "featured": False,
    "name": {"tr": "Kuru Üzüm", "en": "Raisins"},
    "latin": "Vitis vinifera",
    "tagline": {"tr": "Ege'nin çekirdeksiz Sultana üzümü", "en": "Seedless Sultana raisins from the Aegean"},
    "intro": {
      "tr": "Manisa ve İzmir'de yetişen çekirdeksiz Sultana üzümü, Türkiye'yi dünyanın en büyük kuru üzüm ihracatçılarından biri yapar. Doğal güneşte kurutulmuş, yıkanmış, sapı alınmış ve yağlanmış üzümleri renk tipine göre sınıflandırılmış olarak sunuyoruz.",
      "en": "Seedless Sultanas from Manisa and İzmir make Türkiye one of the world's largest raisin exporters. We supply naturally sun-dried raisins — washed, de-stemmed and lightly oiled — sorted by colour type."},
    "details": {
      "tr": ["Sultana Type 7, 8, 9, 10 ve Standart renk tipleri.",
             "Siyah kuru üzüm ve Thompson çekirdeksiz seçenekleri.",
             "Hem perakende hem de unlu mamul ve kahvaltılık gevrek sanayii için.",
             "Taş, sap ve yabancı madde ayıklaması lazerli ve optik makinelerle yapılır."],
      "en": ["Sultana Type 7, 8, 9, 10 and Standard colour types.",
             "Black raisins and Thompson seedless options.",
             "For retail as well as bakery and breakfast-cereal industries.",
             "Stones, stems and foreign matter removed by laser and optical sorters."]},
    "specs": {
      "origin":  {"tr": "Türkiye (Manisa, İzmir, Denizli)", "en": "Türkiye (Manisa, İzmir, Denizli)"},
      "forms":   {"tr": "Yıkanmış, yağlanmış, sapsız", "en": "Washed, oiled, de-stemmed"},
      "grades":  {"tr": "Type 7 · 8 · 9 · 10 · Standart", "en": "Type 7 · 8 · 9 · 10 · Standard"},
      "moisture":{"tr": "≤ %16", "en": "≤ 16%"},
      "shelf":   {"tr": "Uygun koşullarda 18 ay", "en": "18 months under proper storage"},
      "hs":      "0806.20",
    },
    "nutrition": [299, 3.1, 0.5, 79.2, 3.7],
  },
  {
    "slug": "hurma", "slug_en": "dates", "cat": "kurumeyve", "img": "hurma", "gallery": 3, "featured": False,
    "name": {"tr": "Hurma", "en": "Dates"},
    "latin": "Phoenix dactylifera",
    "tagline": {"tr": "Medjool, Deglet Nour, Mabroom, Ajwa ve Mazafati", "en": "Medjool, Deglet Nour, Mabroom, Ajwa and Mazafati"},
    "intro": {
      "tr": "Doğal şekeri, lifi ve mineral içeriğiyle hurma; özellikle Ramazan döneminde yüksek talep gören, yıl boyu satılan bir üründür. Körfez ülkeleri, Kuzey Afrika ve İran'ın en seçkin hurma çeşitlerini ithal ederek toptan ve perakende kanallara ulaştırıyoruz.",
      "en": "Naturally sweet and rich in fibre and minerals, dates sell year-round with peak demand during Ramadan. We import the finest varieties from the Gulf, North Africa and Iran for wholesale and retail channels."},
    "details": {
      "tr": ["Medjool: iri, yumuşak, karamel aromalı premium hurma.",
             "Deglet Nour (Tunus / Cezayir): yarı kuru, altın renkli, dallı veya dalsız.",
             "Mabroom, Ajwa, Sukkari (Suudi Arabistan) ve Mazafati (İran) çeşitleri.",
             "Çekirdekli, çekirdeksiz ve hurma ezmesi seçenekleri; Ramazan dönemi için önceden planlama."],
      "en": ["Medjool: large, soft, caramel-toned premium dates.",
             "Deglet Nour (Tunisia / Algeria): semi-dry, golden, on or off the branch.",
             "Mabroom, Ajwa, Sukkari (Saudi Arabia) and Mazafati (Iran).",
             "Pitted, whole and date paste; advance planning for the Ramadan season."]},
    "specs": {
      "origin":  {"tr": "Suudi Arabistan, BAE, Tunus, Cezayir, İran, Mısır", "en": "Saudi Arabia, UAE, Tunisia, Algeria, Iran, Egypt"},
      "forms":   {"tr": "Çekirdekli, çekirdeksiz, dallı, ezme", "en": "Whole, pitted, on-branch, paste"},
      "grades":  {"tr": "Jumbo · Large · Medium (çeşide göre)", "en": "Jumbo · Large · Medium (by variety)"},
      "moisture":{"tr": "Çeşide göre %18 – 30", "en": "18 – 30% by variety"},
      "shelf":   {"tr": "Soğuk zincirde 12 ay", "en": "12 months in cold storage"},
      "hs":      "0804.10",
    },
    "nutrition": [277, 1.8, 0.2, 75.0, 6.7],
  },
]
